create git api
Helen91/test_guru pull request #13
Opened 2022-11-09 15:16 UTC by Helen91

2022-11-15 16:41 UTC, BubuntuClu requested changes

2022-11-15 16:41 UTC, BubuntuClu commented on app/controllers/user_tests_controller.rb
> +    url = result["html_url"]
наличие какого-то текст в этом поле не гарантирует что запрос прошел успешно. тут может быть ссылка на ошибку или что-то еще

2022-11-15 16:41 UTC, BubuntuClu commented on app/controllers/user_tests_controller.rb
> +    Gist.create(question: @user_test.current_question, user: current_user, url: url )
почему ты в любом случае сохраняешь у себя гист, даже при возможной ошибке в ответе из сервиса?

2022-11-15 16:41 UTC, BubuntuClu commented on app/controllers/user_tests_controller.rb
> +    flash_options = if url
нужно сделать метод в сервисе, вызывая который ты поймешь как отработал сервис и далее сможешь вызвать нужный код. поможет тебе `last_response` в октоките

2022-11-15 16:41 UTC, BubuntuClu commented on app/services/gist_question_services.rb
> +  def initialize(question, client: nil)
может тут вместо `nil` написать `GitHubClient.new`, тогда на 6 строке не будет ветвления

2022-11-16 13:58 UTC, Helen91 commented on app/controllers/user_tests_controller.rb
> +    flash_options = if url
не совсем поняла, но сделала по другому

2022-11-16 17:09 UTC, BubuntuClu commented on app/controllers/user_tests_controller.rb
> +    flash_options = if result.status == 201
вынеси это в метод сервиса `success?`. не стоит выносить наружу реализацию. вдруг тебе надо будет поменять реализацию и вместо правки в сервисе, тебе понадобиться править это везде

2022-11-22 11:15 UTC, merged