create seeeds and methods
Helen91/test_guru pull request #3
Opened 2022-08-01 16:22 UTC by Helen91

2022-08-01 17:37 UTC, BubuntuClu requested changes

2022-08-01 17:37 UTC, BubuntuClu commented on app/models/test.rb
> +    categories = Category.where(title: name)
ты знакома с операцией `join` в запросах. надо это тут использовать, чтобы получить за один запрос к БД нужные данные

2022-08-01 17:37 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.where(level: num)
в таком запросе никак не участвует пользователь. по заданию нужно получить тесты, которые пользователь проходил

2022-08-02 10:59 UTC, Helen91 commented on app/models/test.rb
> +    categories = Category.where(title: name)
переделала на joins

2022-08-02 11:00 UTC, Helen91 commented on app/models/user.rb
> +    Test.where(level: num)
непонятно, написала в slack

2022-08-02 16:46 UTC, BubuntuClu requested changes

2022-08-02 16:46 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.where(id: UserTest.where(user_id: self.id).pluck(:test_id), level: level)
ну, тут тоже самое. используй `join`

2022-08-02 16:46 UTC, BubuntuClu commented on db/schema.rb
> +  create_table "user_tests", force: :cascade do |t|
в Пре нет миграции на это изменение. забыла добавить?

2022-08-02 20:52 UTC, Helen91 commented on app/models/user.rb
> +    Test.where(id: UserTest.where(user_id: self.id).pluck(:test_id), level: level)
переделала

2022-08-02 20:52 UTC, Helen91 commented on db/schema.rb
> +  create_table "user_tests", force: :cascade do |t|
забыла

2022-08-04 16:44 UTC, merged