new controller question
Helen91/test_guru pull request #6
Opened 2022-08-29 14:28 UTC by Helen91

2022-08-29 19:00 UTC, BubuntuClu requested changes

2022-08-29 19:00 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = @test.question.find(params[:id])
этот код дублируется в нескольких методах, надо вынести в метод/колбэк

2022-08-29 19:00 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
добавь тут опцию `shallow: true`, посмотри как изменяться роуты и адаптируй код контроллера

2022-08-30 10:02 UTC, Helen91 commented on app/controllers/questions_controller.rb
> +    @question = @test.question.find(params[:id])
вынесла

2022-08-30 10:02 UTC, Helen91 commented on config/routes.rb
> +    resources :questions
адаптировала

2022-08-30 19:59 UTC, BubuntuClu commented on config/routes.rb
> +  resources :tests, shallow: true do
эту опцию надо добавлять только для вложенных ресурсов. для верхнего уровня она ничего не делает

2022-09-01 10:12 UTC, Helen91 commented on config/routes.rb
> +  resources :tests, shallow: true do
вот какой результат если на верхнем уровне. Если поменять, то получится тоже самое.
```
                          test_questions GET    /tests/:test_id/questions(.:format)                                                               questions#index
                                         POST   /tests/:test_id/questions(.:format)                                                               questions#create
                       new_test_question GET    /tests/:test_id/questions/new(.:format)                                                           questions#new
                           edit_question GET    /questions/:id/edit(.:format)                                                                     questions#edit
                                question GET    /questions/:id(.:format)                                                                          questions#show
                                         PATCH  /questions/:id(.:format)                                                                          questions#update
                                         PUT    /questions/:id(.:format)                                                                          questions#update
                                         DELETE /questions/:id(.:format)                                                                          questions#destroy
```

2022-09-01 10:12 UTC, merged