new views
Helen91/test_guru pull request #7
Opened 2022-09-02 19:24 UTC by Helen91

2022-09-03 07:14 UTC, BubuntuClu requested changes

2022-09-03 07:14 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def question_header(action, test)
передавай сюда явно только объект вопроса. далее ты можешь оценить состояние вопроса, чтобы определить какой заголовок показать. состояние ты можешь определить одним из методов `new_record?/presisted?`

2022-09-03 07:14 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    "https://github.com/#{author}/#{repo}"
от такого метода большого проку нет. он по факту просто вставляет строки в другую строку, почему интреполяцию сразу не сделать на вьюхе?

а вот если тут возвращать уже `link_to`хэлпер, то смысла становится уже больше.

2022-09-03 07:14 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<h1><%= question_header("edit", @question.test) %></h1>
код во вьюхах `edit/new` по сути должен быть одинаковый. как минимум заголовок и форма должны быть общими.
если заголовок вызывать отдельно в каждой вьюхе, то зачем нам метод, который определяет текст, если можем напрямую тут указать нужный текст

2022-09-03 07:14 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<%= form_with(model: @question) do |form| %>
это должно быть внутри формы.

и форма должна строится на двух объектах `@test, @question` . в зависимости от наличия каких то данных в этих объектах рельса сама построит нужный роут для формы. если для редактирования вопроса у тебя роут прямой(без учета тестов), то объект теста надо просто сделать пустым

2022-09-03 07:14 UTC, BubuntuClu commented on app/views/questions/index.html.erb
> +  <% @test.questions.each do |question| %>
это можно вынести в паршиал и рендерить коллекцию  `render @test.questions`

2022-09-03 07:14 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<h1><%= question_header("new", @test) %></h1>
тоже самое что и в `edit` вьюхе

2022-09-03 07:14 UTC, BubuntuClu commented on app/views/questions/new.html.erb
>  <%= form_with(model: [:test, @question]) do |form| %>
объект теста должен быть не абстратный, а конкретный. ты ведь создаешь новый вопрос к конкретному тесту

2022-09-04 12:09 UTC, Helen91 commented on app/helpers/questions_helper.rb
> +  def question_header(action, test)
переделала

2022-09-05 07:55 UTC, merged